### ISSUE TITLE
Can't build and run

### ISSUE THREAD

**Issue by justinhj** [mschuwalow/zio-todo-backend#4]
Having some trouble trying this out. I loaded up in sbt and can build, but run can't find the main class. Same in IntelliJ

**Comment by mschuwalow** [comment]
Hi. Sorry for now i only have a maven build setup. I'll try to get sbt (and maybe mill because i want to try it out)  set up, but this is something that might take a bit of time because I'm only used to maven from work.
For now you should be able to build it with `mvn -pl app package`.

The main class is defined here https://github.com/mschuwalow/zio-todo-backend/blob/develop/app/pom.xml#L30.
If you want to contribute your sbt build setup that would be great.

**Comment by justinhj** [comment]
Oh I see, no problem, I can use maven :) Closing since this is not an issue
