### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tampler** [mschuwalow/zio-todo-backend#6]
Hello Mr.Schuwalow

Thanks for a great project shared!

I started to work with your implementation. I found some of your tests failing. Maybe a bug in ZIO. Could you pls take a look ?
Here's [my project](https://github.com/Clover-Group/zio_front)

Thanks,
Boris

**Comment by mschuwalow** [comment]
Sure. I'll try to get back to you this week

**Comment by mschuwalow** [comment]
I had a look at your project and the issue seems to be the updated http4s version.
Downgrading to 0.20.0-M3 resolves the issue.

I have also upgrade all version here, you can take a look at https://github.com/mschuwalow/zio-todo-backend/commit/32d3edc8a43a9ab8e6a17ecae2d896547fbc8181 for the changes necessary to make this work with http4s 0.20.1
